spring:
  application:
    name: fitness-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://8.163.7.156:64321/fitness?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
#    username: root
#    password: X7#k9P$m2@qL!vWc
    url: jdbc:mysql://localhost:3306/fitness?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
    # url: jdbc:mysql://localhost:3306/fitness?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    # username: root
    # password: lnpbqc
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000, expireAfterWrite=10s # 最大1000条，写入后10秒过期

springdoc: # 生产记的关闭
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

wx:
  miniapp: # todo 后续更改
    client-app-id: "wxdc02d8b2987dc20d"
    client-app-secret: "fa468b64ccf3a8ec5b2f8f539f13c5a2"
    coach-app-id: "wxe68f2a925e5831ab"
    coach-app-secret: "1e284db5ab7abbcaf17ee8a1b76965a7"

jwt:
  secret: fitness-admin-secret-key-2026-change-in-production
  expiration: 86400000

server:
  port: 8081
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  ssl:
    enabled: true
    key-store: classpath:ssl/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: tomcat

upload:
#  path: /home/zfxt/formyself/fitness-admin-all/fitness-java/uploads # 我不是linux
  path: classpath:uploads